### PR TITLE
Fix switch toggles not changing when state received from ESP

### PR DESCRIPTION
**Pull request by jesserockz**
https://stackoverflow.com/a/55994717

### CODE REVIEW

**Comment by RebbePod** [comment]
@jesserockz It seems that now the number boxes and slider aren't changing on state publish, is it possibly related to this?

**Comment by jangrewe** [comment]
@jesserockz I was the dude that talked to you about this issue on Discord, and confirmed that your fix was working with the external JS file - but it seems that JS file hasn't made it into the ESPhome releases yet, or do i need to run some magic to have those changes pulled, too?

**Comment by RebbePod** [comment]
@jangrewe it's working for me.

**Comment by jangrewe** [comment]
@RebbePod Do you use `local: true`?

**Comment by RebbePod** [comment]
No

**Comment by jangrewe** [comment]
Then i'm not surprised that it's working for you - but that's also exactly why i'm following up on this, see above. 😉

**Comment by RebbePod** [comment]
The PR has been merged if you'd like to run it offline you'd have to redownload the js file

**Comment by jangrewe** [comment]
And that's exactly what i'm asking for: how do i update the local files correctly? I assume it's pulling `esphome-webserver`, but i don't know where/how that is initially done, because i didn't have to do this initially.
I just set `local: true` and the files were included - without me downloading anything.
I'm happy to open a MR for `esphome-docs` once i know what/how to do it.

**Pull request merged**
