### PR TITLE
Use pushed state for UI

### LINKED ISSUE #6: Bug: Toggle state doesn't always update when switch state does
In V2 version of UI sometimes when using automations state updates but toggle component does not reflect it (while text status always does).
Possible culprit: https://github.com/esphome/esphome-webserver/blob/d918bc1da205f6af27b985407df7de252d1c6f02/v2/esp-entity-table.ts#L120
I would fix it and submit a merge request, but I do not write in LitElements and I am not entirely sure that I understand how you manage state.

I would be very grateful for a fix.
Kind regards

### PR DESCRIPTION
**Pull request by alexyao2015**
fixes #6 

This optimistically sets the state and waits for the pushed state to return. If the state isn't pushed back, the toggle returns to the previous state.

There were also a number of typescript errors that I tried to fix, but didn't have a chance to get to all of them.

This also adds a devcontainer environment.

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]
Would have been nice to get these changes in different PRs, especially since I don't really know typescript/lit that much (read: don't know lit at all).

Overall looks OK to me.

@wilberforce can you please review the changes?

**Comment by wilberforce** [comment]
@jesserockz Looks ok to me...

**Comment by alexyao2015** [comment]
> Would have been nice to get these changes in different PRs, especially since I don't really know typescript/lit that much (read: don't know lit at all).

Yeah sorry about that. I barely knew much about the langs at all as well, so the PR kinda evolved as I made changes (that's why it's a bunch of various changes).

@wilberforce I haven't made any other changes to the main esphome repo or anything else. Will you be updating the other areas that need to be updated?

**Comment by wilberforce** [comment]
> I haven't made any other changes to the main esphome repo or anything else.
The only to do is updated the standalong embedded include file. Let's let this settle first...
Anything that gets the files via the internet should have the updated switch...  

The version should have been bumped.. so it's easy to tell if it has updated..

https://github.com/esphome/esphome-webserver/blob/main/package.json#L3

**Pull request merged**
